version: 2.1 
orbs:
  aws-ecr: circleci/aws-ecr@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
      - aws-ecr/build_and_push_image:
          filters:
            tags:
              only: /v.*/
            branches:
              only: main
          account-url: ACCOUNT_URL
          repo: nacomer-express
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: start
          command: echo "ci start"
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: install-yarn
          command: yarn
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test