name: CI Test and AWS ECS deployment  
on:
  push:
  pull_request:
    branches: [main]
  
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14.15.1-alpine3.12

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
    env:
      DB_HOST: postgres
      DB_NAME: nacomer
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_KEY: ${{ secrets.JWT_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Create Database
      run: yarn create-db

    - name: Setup Database
      run: yarn setup

    - name: Run test
      run: yarn test
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials # AWSアクセス権限設定
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR # ECRログイン処理
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR # ECRイメージPush
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        TAG: ${{ github.sha }}
      run: |
        IMAGE_TAG=${TAG}
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Save docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        TAG: ${{ github.sha }}
      run: |
        IMAGE_TAG=${TAG}
        docker save $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG > nacomer_api.tar

    - name: Upload docker image
      uses: actions/upload-artifact@v2
      with:
        name: nacomer_api_image
        path: nacomer_api.tar

    - name: Render Amazon ECS task definition # ECSタスク定義ファイルレンダリング
      id: render-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: aws/task-definition.json # レポジトリ以下のタスク定義ファイルがあるPath
        container-name: nacomer-api-service
        image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}:${{ github.sha }}

    - name: Deploy to Amazon ECS service # ECSサービスデプロイ
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-container.outputs.task-definition }}
        service: nacomer-api-service
        cluster: nacomer-api-cluster