name: CI Test  
on:
  push:
  pull_request:
    branches: [main]
      
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14.15.1-alpine3.12

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
    env:
      DB_HOST: postgres
      DB_NAME: nacomer
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_KEY: ${{ secrets.JWT_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Create Database
      run: yarn create-db

    - name: Enable uuid_generate()
      run: sh ./db/enable_uuid.sh postgres nacomer postgres

    - name: Setup Database
      run: yarn setup

    - name: Run test
      run: yarn test-only

    - name: Lint code
      run: yarn lint
